### ISSUE TITLE
provide information about release cycles

### ISSUE THREAD

**Issue by steros** [PAYONE-GmbH/magento-2#153]
For me it's entirely unclear when a release will happen.
As the master is not a definite, clean and tested build. One has to rely on releases in production.
Unfortunately the master often contains critical bugfixes. Yet it takes very long until a new release is submitted. Also it is not clear when such a release will happen at all.

Please provide some information like:
- how often do you build
- what is the criteria for a new release
- ...

**Comment by fjbender** [comment]
We have identified the unclear release cycle as a potential problem as well, and I'd like to take in suggestions on what is preferred by customers, developers, and agencies.

Would you prefer:
* A periodic release cycle: e.g. monthly, bi-weekly etc.
* A release cycle based on the contents (i.e. whenever a certain amount of changes come around)
* Something entirely different

We definitely don't recommend running the master branch in production, as you correctly mentioned. However, we do indeed test each pull request independently (which is why they often times take a while to merge) and do some pre-release testing whenever we're planning one. So in general, the master branch should be suitable for testing/staging systems.

**Comment by steros** [comment]
I guess a periodic cycle would be best for continuity. But a monthly release cycle might be too slow for critical bugs. ( Although better than nothing ^^ )

A release cycle based on contents would need to be split though.
- Immediate releases for critical bug fixes
- less frequent for non critical bugs
- intermittent releases for new features if committed

Maybe a mix of both can be achieved? Like:
- timely bug-fix releases for critical bugs
- monthly releases for new features and non critical bug fixing
