### ISSUE TITLE
Debitcard not working in new version.

### ISSUE THREAD

**Issue by D-David11** [PAYONE-GmbH/magento-2#186]
Hello,

I have updated payone to 2.2.1 in my magento 2.1.10. All payment method are working except debitcard. This payment method is in test mode and I am using following detail while payment.

Country : DE
IBAN : DE85123456782599100003

I am getting following error :
703 - The transaction could not be executed..

Note : All configuration are default only the mode is in test mode.

**Comment by fjbender** [comment]
@D-David11 Error 703 means that the transaction was denied due to the IP Velocity Check (too many orders from the same IP Address). For testing purposes it is advised that you disable all Velocity Checks in the Payone Merchant Interface. This is not a module issue.

For further information on the Velocity Check configuration, please contact our support team through phone or mail.

Thanks!

**Comment by D-David11** [comment]
Thanks,

But Now I am getting this error "This payment method is currently not available. Please use PayPal, credit card or Sofortüberweisung." in debit card.

**Comment by fjbender** [comment]
This, unfortunately, also sounds more like a problem specific to your Merchant Account and not to the module - the Support Team will gladly help you.
