### ISSUE TITLE
Feature Request: Amazon Pay

### ISSUE THREAD

**Issue by david-fuehr** [PAYONE-GmbH/magento-2#191]
We plan to use _amazon pay_ as payone payment method. As PayOne already supports this method:

Is there any information when this method will be implemented in magento2 module?

**Comment by fjbender** [comment]
We currently have it on our roadmap. However, it is not quite finished yet.

Currently, creating a new order already works, but we're still working on error handling and backoffice processes. See https://github.com/FatchipRobert/magento-2/tree/MAG2-23-Amazon-Pay

**Comment by david-fuehr** [comment]
Thanks @fjbender for your fast response.

The last commit in that branch is from november 2017. Is there a planned release date?

Also: Who is maintaining this feature (@FatchipRobert ?) and is there a ticket system so that contribution would be generally possible?

**Comment by fjbender** [comment]
We have been pushing it far back in our roadmap because demand was low and complexity is high.

All coordination of features is done by @hreinberger and me. We have a ticket system, however, it's internal and currently not open for contributors (as we never had the case that anybody wanted to contribute in a way that required them to join the ticket system).

If you contact me at integrations@bspayone.com I can get you up to speed on the details and we can work something out :)

**Comment by chopemann** [comment]
Are there any news about this topic? We are also waiting for the amazon pay integration.

**Comment by fjbender** [comment]
This feature is currently in active development again. We expect some updated commits in the branch linked above during this week.

**Comment by hreinberger** [comment]
fixed in 2.5.0
