### ISSUE TITLE
Article list faulty or incomplete - Magento API

### ISSUE THREAD

**Issue by andreaspenz** [PAYONE-GmbH/magento-2#213]
Hello,

i encounter an error in Magento v2.2.6 and your Module v2.2.0. 

Reproduce the Problem:

- Place a new order in Magento with multiple items and pay with CC / Visa (in my case 3 items)
- Create a new invoice trough the Magento-API for some of the ordered items (in my case the first 2 items) with a request similar to the following:

```
POST https://example.com/rest/V1/order/1/invoice
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer xyz

{  "capture": true,  "items": [    {      "order_item_id": 1,      "qty": 1      },    {      "order_item_id": 2,      "qty": 2    }  ],  "notify": true }
```

The response from the Payone-API is "Article list faulty or incomplete". 

Shouldn't it be possible to capture only some of the items?

**Comment by fjbender** [comment]
Do you have the Payone TXID for that transaction? I'll check the logs.

**Comment by andreaspenz** [comment]
The TXID is 299524879

**Comment by fjbender** [comment]
For the capture request, all items are sent, but the amount is correct.

Maybe there's a bug in \Payone\Core\Model\Api\Request\Capture::getInvoiceList. I'll see if I can test this further.

**Comment by fjbender** [comment]
I couldn't try anything out yet. However, I have the feeling that the problem is here:

https://github.com/PAYONE-GmbH/magento-2/blob/a43fd28a0f7aad62574dcd8871d8cd2c39126b72/Model/Api/Request/Capture.php#L73-L101

This method relies on the Base Helper to pass the invoice parameter from the request:

https://github.com/PAYONE-GmbH/magento-2/blob/a43fd28a0f7aad62574dcd8871d8cd2c39126b72/Helper/Base.php#L107-L116

Is the request and/or parameter available in an API context?

**Comment by mw-prakash** [comment]
when some extra fee to charge is added it fails. 
Article list faulty or incomplete
