### ISSUE TITLE
Bug in extension crashes Magento when a store view is removed

### ISSUE THREAD

**Issue by ostukalovprovectus** [PAYONE-GmbH/magento-2#226]
When a store view is removed from Magento 2 (2.2) with installed PayOne extension, Magento crashes with an error:

> Magento\Framework\Exception\NoSuchEntityException: Requested store id=7 is not 

You keep in the config information such as
`# config_id, scope, scope_id, path, value
'818', 'store', '7', 'payone_protect/creditrating/payone_consumerscore_sample_counter', '99'
!!!`

But Magento does not have a scope **store**, but it has a scope **stores**!

And when a Store View is removed, Magento cannot clean it, as it looks for stores, not store.

Magento tries to read it here, but fails...
> /magento2/vendor/magento/module-config/App/Config/Source/RuntimeConfigSource.php

You have to fix your module in 2 places
> /magento2/app/code/Payone/Core/Helper/Consumerscore.php - line 103

and 
> /magento2/app/code/Payone/Core/Helper/Database.php - line 188

**Comment by T-Kuchel** [comment]
Hello @ostukalovprovectus ,

thank you for this information!
Are there any further details on this issue? Maybe a log or something else?

regards
Timo

**Comment by AntonKryvoruchko** [comment]
Here:
https://github.com/PAYONE-GmbH/magento-2/blob/adc1d10118d5ea2236e72bbbce4dfac46a9b468b/Helper/Consumerscore.php#L103
you use wrong scope constant:
ScopeInterface::SCOPE_STORE
instead of
ScopeInterface::SCOPE_STORES
You have to use ScopeInterface::SCOPE_STORES because when magento remove store it use in
https://github.com/magento/magento2/blob/32e14dbda4da211f86fc25ef62a42378448fa434/app/code/Magento/Store/Model/Store.php#L1238
exactly ScopeInterface::SCOPE_STORES
but not ScopeInterface::SCOPE_STORE !
So when magento tries to load current config from DB here
https://github.com/magento/magento2/blob/32e14dbda4da211f86fc25ef62a42378448fa434/app/code/Magento/Config/App/Config/Source/RuntimeConfigSource.php#L83
exception is thrown
Magento\Framework\Exception\NoSuchEntityException: Requested store id is not found

**Comment by T-Kuchel** [comment]
Hello @ostukalovprovectus ,

many thanks!
We will investigate on this and come back to you as soon as possible.

regards
Timo
