### ISSUE TITLE
Wrong Status for Orders with only downloadable products

### ISSUE THREAD

**Issue by alexandergolz** [PAYONE-GmbH/magento-2#270]
> After checking this fix, it appeared that it doesn't work as expected.
> 
> The virtual order should be in state "complete" after payment went through.
> With your current code it would remain at "processing".
> 
> Line 78 of Model/Plugins/State.php is:
> 
> } elseif ($currentState === Order::STATE_PROCESSING && !$order->canShip() && **!$order->getIsVirtual()) { // added !$order->getIsVirtual()**
> 
> but should be:
> 
> } elseif ($currentState === Order::STATE_PROCESSING && !$order->canShip() && **$order->getIsVirtual()**) { // added $order->getIsVirtual()
> $order->setState(Order::STATE_COMPLETE)->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_COMPLETE));
> 
> Regards
> Thomas

I'm on Magento 2.3.3 and orders with only downloadable Products now get status "Processing" instead of "Closed" (which they did before this commit). But it should be "Complete". Your comment addresses this issue but was not included in this commit, am I right?

Regards

Alexander

_Originally posted by @alexandergolz in https://github.com/PAYONE-GmbH/magento-2/pull/263#issuecomment-559201767_

**Comment by fjbender** [comment]
I wasn't the one working on this PR, but I suppose, the way we build it is intentional. QA shows that with the PR, the configured status mapping is respected equally for physical and virtual goods.

Can you share your status mapping configuration?

**Comment by fjbender** [comment]
From the discussion in #263 (@webpeaks63):

> The status for physical order should only show "complete" after shipment, not after payment. For downloadable orders the order status should be complete after payment. This is not confusing, it is the way it should go.

I'm having a hard time figuring out what the right behavior is. We aim to make status transitions configurable and not hard code them into the logic, as different merchants have different requirements here. @webpeaks63 suggests, it should be hard coded for downloadable orders. This conflicts.

How would you handle it in the cased of mixed orders (i.e. one physical and one virtual product)?

**Comment by webpeaks63** [comment]
You may have a look at the core magento PayPal Express integration, where the order status does work perfect with virtual orders.

Only the Payone Extension is showing that issue.

Beside discussions how this could or should be fixed in your Payone M2 extension:

1. Physical orders are "complete" when they are shipped.

2. Virtual orders (downloadable goods, or gift cards etc.) are "complete" after payment.

3. Mixed orders (physical and virtual products) are physical orders. They are "complete" after all physical products are shipped.

This is not a custom merchant requirement!

I am curious to see how you want to integrate this into your status mapping... (to avoid a "hard coded solution").

Best Regards
Thomas

**Comment by fjbender** [comment]
This makes sense.

We'll update the behavior for virtual orders accordingly.
