### ISSUE TITLE
paypal charge two time for same order. 

### ISSUE THREAD

**Issue by nilarocks** [PAYONE-GmbH/magento-2#279]
We have some issue in paypal.
 user place order using payone paypal method. order successfully placed. But user charged two time for same order. 

See below screenshot
![72141834-94678500-33b9-11ea-822c-79e9f092ccef](https://user-images.githubusercontent.com/14245197/72891985-7562de80-3d3b-11ea-8dd1-013f2efc7f97.png)

you can see Order is 97 euro but Total paid is 194 euro.

Also see PAYONE Protokoll - Status.
![image](https://user-images.githubusercontent.com/14245197/72142095-fe802a00-33b9-11ea-9e80-19a32ba1c65d.png)

Same time paid status show two time.

**Comment by hreinberger** [comment]
Hi @nilarocks 
thanks for your feedback.
This looks like our platform sent the "paid" callback twice, which made the shop think the paid amount is doubled. This could happen due to performance issues while receiving the paid status or general internet hiccup. We'd love to further investigate this transaction though, so could you get in touch with our tech support at tech[dot]support[at]bspayone.com? You can refer to this thread and please tell them your merchant ID and the txid in question.
Thanks!

**Comment by omargits** [comment]
@hreinberger we having kind of same issue . Appointed status is double and because of that two invoices created one is with 0.00 and other is with normal amount. 

if you found any solution specially if it on magento side any idea how to debug or catch the error please guide us 
thanks
