### ISSUE TITLE
why automatically Invoice generate for payment method  credit card?

### ISSUE THREAD

**Issue by nilarocks** [PAYONE-GmbH/magento-2#304]
we have issue when user paid order using creditcard-mastercard. 
we have set status mapping  Transactionstatus-message:  APPOINTED and magento Status: Processing. 
when order paid magento status show completed and invoice generated automatically.
PAYONE Protokoll - Status show Two Items
1. appointed
2. Paid

Is it issue from magento or module?

**Comment by hreinberger** [comment]
Hi @nilarocks 
this is actually by design. When using the authorization method "authorization" the cashflow will be triggered instantly. In this case you will receive the statuses "appointed" and "paid" shortly after each other. When an authorized payment receives "paid" our plugin will automatically set the order to completed and create an invoice. This is in line with german laws, where receiving money for an order should create a receivable and every receivable should be reflected by an invoice (though you should check yourself if this also applies to your usecase)

You can switch whether the invoice will be sent to the customer in the plugin settings (PAYONE --> General --> Emails). You could also switch the authorization method to "preauthorization" (globally or for single payment methods). 

In this case, the cashflow won't be triggered immediately and you'll only receive the "appointed" status. Though you would have to create the invoice yourself, which would then trigger the cashflow. More on this here: https://docs.payone.com/display/public/INT/Magento+2+Plugin#Magento2Plugin-CollectingandReturningMoney 

If you need assistance in reflecting your desired workflow and usecase, please get in touch with our tech support team at tech.support[at]payone.com

kind regards and stay safe!

**Comment by nilarocks** [comment]
Thank For reply 
but its happen only for 2 orders, other orders are working fine. I mean order status show "Processing"

**Comment by hreinberger** [comment]
hmmmmm in this case I'd also advise you get in touch with our tech support to have a look at the actual orders. I'd like our support staff to evaluate whether this may also be a configuration error. When you contact our support, please also provide a link to this issue, so our support people can get a full picture on this issue.

**Comment by nilarocks** [comment]
where is contact your tech support? can you please give me link of tech support?

**Comment by hreinberger** [comment]
Hi @nilarocks 
just write them a mail at tech.support@payone.com :)
