### ISSUE TITLE
Forward of transaction status does not work properly

### ISSUE THREAD

**Issue by Wohlie** [PAYONE-GmbH/magento-2#316]
Hi, we have updated the module from 2.6 to 2.8 for 2 months now. Since this update, we have repeating issues with the transaction status forward logic of the module. In some cases, the status is not forwarded to the defined URL.

I think the problem is the short connection timeout
https://github.com/PAYONE-GmbH/magento-2/blob/03e36665697d590434f873d4657da0dd6880ccab/Model/TransactionStatus/Forwarding.php#L124-L134
of change https://github.com/PAYONE-GmbH/magento-2/commit/0b2e165b72569c5966939aa909e04e81f52a9534 which includes an “asynchronous” way of the transaction status forward process.

It is possible that you will change the implementation to a real asynchronous process that will be fail-safe:
* Processing of transaction status forwards should be performed by a cronjob or message queue like rabbitmq. That will eliminate the 100ms connection timeout.
* Retry a forward if a custom URL will not be return HTTP status code 200

**Comment by ewasser** [comment]
This is a real issue. Let me explain. The `100ms` includes the time for a DNS lookup and slow answering DNS services are more common than you think. Let me explain the details in the call:

1. The request starts and also the countdown starts.
2. `curl` tries to resolve the domain behind `$sUrl`. 
3. The underlying OS (we're taking Linux as example) will ask the DNS with an timeout of `5s`. This is the standard under the default configuration (see `man resolv.conf` and `#define RES_TIMEOUT 5` from `/usr/include/resolv.h`). The DNS query can be answered with a cached entry but even that costs time. Or the UDP package with the answer gets lost in the internet traffic.
4. If anything from the above occurs, we're in big trouble. The OS can't retry the DNS request because after `100ms` the `curl` request will be canceled hard and the update of the transaction status is lost because there are __no__ retries implemented.

My suggestion:

1. Like @Wohlie already said: Queue the calls if RabbitMQ is configured within the Magento 2 instance.
2. (Quick and dirty) Increase the timeout from `100ms` to `2500ms` (better `5500ms`) so a slow network will not kill the update of the transaction status. Give the DNS timeout a chance.

Thank you.

**Comment by fjbender** [comment]
Sorry, this issue somehow went by unnoticed.

The "asynchronous" part of the change mentioned above was intended to decouple the receiving of the notify message from our platform from the forwarding process. This had to be done since our platform works with a timeout of 10000ms, which could be reached before completion of all the forwarding, if there were more than a couple forwarding endpoints configured.

I would opt for @ewasser 's suggestion of increasing the timeout for the moment. While a RabbitMQ implementation does sound promising, I'd like to solve this issue quickly.
