### ISSUE TITLE
I am getting this exception when using on 2.4.4

### ISSUE THREAD

**Issue by HemendraXtwo** [PAYONE-GmbH/magento-2#471]
1 exception(s):
Exception #0 (Exception): Deprecated Functionality: mb_convert_encoding(): Passing null to parameter #1 ($string) of type array|string is deprecated in .../vendor/payone-gmbh/magento-2/Helper/Toolkit.php on line 213

Exception #0 (Exception): Deprecated Functionality: mb_convert_encoding(): Passing null to parameter #1 ($string) of type array|string is deprecated in ....../vendor/payone-gmbh/magento-2/Helper/Toolkit.php on line 213

**Comment by janteuber** [comment]
Hello @HemendraXtwo ,

Thank you for your message.

In order to be able to help you I would like to ask you to write a mail to tech.support@payone.com.
In this mail please write detailed where exactly the error occurs and which merchant ID you use.

The colleagues will then take a look at what the error could be.

Thank you very much.
