### ISSUE TITLE
Move redirected Orders into Pending Payment State so they will be cancled by Magento Cron

### ISSUE THREAD

**Issue by itterror** [PAYONE-GmbH/magento-2#472]
Hello,

after in installing the module in our store we noticed we have a bunch of orders which are stuck in the waiting for payment state.
The user succesfully got redirected to the paypal site but then quits the checkout process there. Currently all these orders are left in the state pending. Pending is a state the default Magento Cron Job does not cancel orders. (Which obviously should happen)

Is there a way to move orders, which are awaiting their payment/return from the user into the pending payment state?
I figured this should be possible through the status mapping, but sadly this only accounts for actual status updates by payone but not from responses through the api (i have the status "REDIRECTED" as response in the first API call). I only can map txaction which does no help in this case, as this response only comes when the payment was succesfull.

Am I missing something or is something that wasn't considered before?

Regards

**Comment by janteuber** [comment]
Hello @itterror ,

Thank you for your message.

In order to be able to help you I would like to ask you to write a mail to [tech.support@payone.com](mailto:tech.support@payone.com).
In this mail please write detailed where exactly the error occurs and which merchant ID you use.

The colleagues will then take a look at what the error could be.

Thank you very much.
