### ISSUE TITLE
storage is undefined after failed 3D-Secure Password

### ISSUE THREAD

**Issue by OvalMedia** [PAYONE-GmbH/magento-2#475]
Magento 2.4.3-p1
Module: 3.5.0

Customers tend to be confused by the necessity to enter another password after entering their credit card data in the shop. This results in a redirect back to the shop which fails with an error in the JS console (Uncaught TypeError: storage is undefined) pointing to line 178 in the file vendor\magento\module-customer\view\frontend\web\js\customer-data.js.

All JS stops and the page is stuck with a spinner. 

All works fine if the correct password is entered.

Not sure if this is related to this issue: https://github.com/PAYONE-GmbH/magento-2/issues/464

**Comment by janteuber** [comment]
Hello @OvalMedia ,

Thank you very much for the message.

In principle, we are not aware of the case. So that we can take a closer look at the case, I would ask you to write an email to tech.support@payone.com.

Please include in the mail when this incident occurred and especially at which merchant (Merchant-id) this happened.

Thank you very much.
