### ISSUE TITLE
PayOne ApplePay compatibility with Magento Cloud

### ISSUE THREAD

**Issue by hannes011** [PAYONE-GmbH/magento-2#493]
Hi,

We are currently trying to upload the ApplePay Certificate in the configuration area of Magento Admin Panel. Unfortunately, Magento Cloud is throwing the error "Warning: mkdir(): Read-only file system" since the upload is causing a mkdir-call for "vendor/payone-gmbh/magento-2/ApplePay":

\Payone\Core\Model\System\Config\Backend\Upload::moveFile#100

Solution would be (since Magento Cloud has write permissions only in directory "var") to change the path in \Payone\Core\Helper\ApplePay::getApplePayUploadPath#43 to "var/payone-gmbh/ApplePay" or so.

I'm currently using PayOne version 3.7.0

**Comment by janteuber** [comment]
Hello @hannes011 ,

Thank you very much for your message.

I have forwarded this issue to my colleagues and will get back to you as soon as there are any news.

**Comment by janteuber** [comment]
Hello @hannes011 ,

We have refactored the file upload so that it should also work for Magento Cloud users: (Which we can't test due to lack of access to a Magento Cloud store).

The solution is also built backwards compatible.
So new files are uploaded to the new location.
Old files from before the update will be recognized and loaded accordingly as long as no new upload has taken place.

The old folder was SHOPROOT/vendor/payone-gmbh/magento-2/ApplePay/.
The new folder is SHOPROOT/var/payone-gmbh/ApplePay/

Can you please have a look if this Pull-Request fits for you.

**Comment by oehmiche** [comment]
Hi @janteuber,

we are running the PayOne-integration (version 3.17.2) on Adobe Commerce for Cloud 2.4.8-p5.
We want to integrate Apple Pay as well, so we tested your bugfix (https://github.com/PAYONE-GmbH/magento-2/pull/498) (see the attached patch-file [payone-applepay.patch](https://github.com/user-attachments/files/32614999/payone-applepay.patch)) and it works as desired .
Can you please reopen this issue and the linked Pull-Request?
Kind regards
Odilo
