### ISSUE TITLE
Issue with canceled orders

### ISSUE THREAD

**Issue by ms-bm** [PAYONE-GmbH/magento-2#536]
Hi all,

we noticed several cases in which Payone Transactions have the order number of a cancelled order as reference number, while at the same time there is a second order placed seconds after the cancelled order which is set to processing. 

I see that this happens in Model\Handler\Cancellation, where first order gets cancelled and a new quote is created by cloning the quote from the first order. This is done in order to prevent losses of quotes in certain cases.

 However, this makes it difficult for the merchant to relate a payment he sees in the Payone Portal to the actual order in Magento 2. Is there a way to deal with this issue?

**Comment by janteuber** [comment]
Many thanks for your PR.

We have looked at the PR and are happy to incorporate it into our plugin.

Thanks again for your effort.

**Comment by FatchipRobert** [comment]
Model\Handler\Cancellation is used when a customer is redirected to the payment service and cancels its payment there.
The Cancellation handler only recreates the basket of the customer.

I think what you mean is the "Substitute Order" mechanic.

When a customer is redirected to a payment service and he is still surfing around in your shop and checkout in a different tab, then we cancel the initial order to prevent fraud.
When the initial payment process then is paid (with the cancelled order) a new "substitute order" is created since a order cannot be uncanceled in Magento.

For these orders I added a new display with a link to the original order or the substitute order in PR #564 
Hope that helps.

<img width="1383" alt="MAG2-325_1_cancelled_order" src="https://github.com/user-attachments/assets/f31ea35d-d8b0-44f8-b25e-d2ed743b041a">
<img width="1385" alt="MAG2-325_2_substitute" src="https://github.com/user-attachments/assets/efc3fb32-32af-4011-b1e3-c1e098d6b4d3">
